name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build the package
        run: mvn --batch-mode -DskipTests package

      - name: Run the unit tests
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
      - name: List files in the repository
        run: ls -la
      - name: Build and push the image
        run: |
          docker login --username jakobrangel --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/jakobrangel/lockbox:latest --file Dockerfile .  
          docker push ghcr.io/jakobrangel/lockbox:latest